### ISSUE TITLE
AttributeError when calling RGBColor method fromHEX

### ISSUE THREAD

**Issue by ElSrJuez** [jath03/openrgb-python#14]
I am getting an error when trying to convert a HEX string to `RGBColor `using the provided method `fromHEX`:

```
Exception has occurred: AttributeError
type object 'RGBColor' has no attribute 'fromHEX'
  File "xxxxx.py", line yy, in zzz
    backColor = RGBColor.fromHEX('#800000')
```

In addition, in VSCode IntelliSense doesnt show the `fromHEX `method, even though interestingly enough it **_does_** show `fromHSV` correctly

**Comment by jath03** [comment]
`fromHEX` was added in the latest git version, but hasn't been included in a pypi release yet.  To install the latest git version, you will have to uninstall `openrgb-python` and then install with the instructions in the README for the newest version.
