### ISSUE TITLE
OpenRGBClient() hangs on update_profiles() (Win10)

### ISSUE THREAD

**Issue by Jaklans** [jath03/openrgb-python#20]
Running the example file, the script hangs without providing any error. Debugging the program, the last function to execute is requestProfileList(). It sends the header, then gets to line 95: self.sock.recv_into(header) before hanging indefinitely.

The client shows up in the OpenRGB SDK Server tab. I have the following devices:

X570 I Aorus Pro WiFi
SteelSeriesRival 300 Mouse

Using openrgb-python version 0.2.6 on python 3.9.2

**Comment by anar4732** [comment]
some here

**Comment by Jaklans** [comment]
Ugggh, found the issue. The feature to save/load the profiles is not in the release version of the OpenRGB SDK Server. Its a newer feature. Since the functionality does not exist, the server ignores it, and the client freezes. This should probably be noted in the readme or fixed so their is some sort of timeout error

**Comment by jath03** [comment]
Can you guys make sure that the latest git version fixes this issue before I make a pypi release?

**Comment by MaximilianGaedig** [comment]
> Can you guys make sure that the latest git version fixes this issue before I make a pypi release?

Yes, it works now.
