### ISSUE TITLE
Cannot load local profiles

### ISSUE THREAD

**Issue by rockerbacon** [jath03/openrgb-python#27]
[LocalProfile.unpack](https://github.com/jath03/openrgb-python/blob/cb5230e10184aff271e8091cfa76a84f6c760337/openrgb/utils.py#L520) is returning `None` which makes the loading of a local profile fail. Loading the exact same profile from the server works fine.

Here's the terminal output of the error:
```
Traceback (most recent call last):
  File "/home/vitor/.local/bin/load-rgb-profile", line 6, in <module>
    client.load_profile('default', True)
  File "/home/vitor/.local/lib/python3.9/site-packages/openrgb/orgb.py", line 339, in load_profile
    controllers = utils.LocalProfile.unpack(f).controllers
AttributeError: 'NoneType' object has no attribute 'controllers'
```

The profile was created in the OpenRGB GUI, I've attached it below:
[default.zip](https://github.com/jath03/openrgb-python/files/6331795/default.zip)

A quick look at the unpack code suggests it does not support the file version.

**Comment by rockerbacon** [comment]
The profile version was bumped to 2 in [this commit](https://gitlab.com/CalcProgrammer1/OpenRGB/-/commit/827b75320cd8de9f458b794d106add53e9fa38a6). The current unpack function only supports version 1.

**Comment by rockerbacon** [comment]
Attempting to load version 2 profiles using the code for version 1 did not work.

**Comment by jath03** [comment]
Does that fix it?
