### ISSUE TITLE
OpenRGBClient() fails on recent builds in linux

### ISSUE THREAD

**Issue by shawnc722** [jath03/openrgb-python#29]
The same builds work fine in windows, using the OpenRGB protocol version 1. When connecting to the server on linux, it fails and the OpenRGB window shows it tried to use protocol version 2. The same code runs fine on version 0.5 of OpenRGB, and it was running on the nightly builds until recently.
Here's the crash log:
```Traceback (most recent call last):
  File "/SharedData/RGB/visualizer.py", line 28, in <module>
    client = OpenRGBClient()
  File "/home/shawn/.local/lib/python3.8/site-packages/openrgb/orgb.py", line 267, in __init__
    self.comms.requestDeviceNum()
  File "/home/shawn/.local/lib/python3.8/site-packages/openrgb/network.py", line 180, in requestDeviceNum
    self.read()
  File "/home/shawn/.local/lib/python3.8/site-packages/openrgb/network.py", line 118, in read
    self.callback(device_id, packet_type, buff[0])
  File "/home/shawn/.local/lib/python3.8/site-packages/openrgb/orgb.py", line 282, in _callback
    self.comms.requestDeviceData(x)
  File "/home/shawn/.local/lib/python3.8/site-packages/openrgb/network.py", line 173, in requestDeviceData
    self.read()
  File "/home/shawn/.local/lib/python3.8/site-packages/openrgb/network.py", line 137, in read
    self.callback(device_id, packet_type, utils.ControllerData.unpack(data, self._protocol_version))
  File "/home/shawn/.local/lib/python3.8/site-packages/openrgb/utils.py", line 464, in unpack
    start, metadata = MetaData.unpack(data, version, start)
  File "/home/shawn/.local/lib/python3.8/site-packages/openrgb/utils.py", line 411, in unpack
    start, val = parse_string(data, start)
  File "/home/shawn/.local/lib/python3.8/site-packages/openrgb/utils.py", line 99, in parse_string
    val = struct.unpack(f"{size}s", data[start:start + size])[0].decode()
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xd0 in position 0: invalid continuation byte```
If there's any way I can help out with figuring out this issue please let me know!

**Comment by jath03** [comment]
What versions of openrgb-python and openrgb are you using?  Can you send screenshots of OpenRGB's software pane on the Information tab from each OS?

**Comment by shawnc722** [comment]
I've tested with builds from the last week or so on linux and seen the same problem on each. Just built from source of the current master and I'll download the equivalent package on windows. Here's the linux screenshot:
![Screenshot from 2021-04-29 01-00-35](https://user-images.githubusercontent.com/45184146/116504593-a4dd9080-a886-11eb-910d-1e3ac4740a8e.png)
Running openrgb-python 0.2.8 on linux, and I'll boot into windows and post the rest ASAP.

**Comment by shawnc722** [comment]
Here's windows:
![image](https://user-images.githubusercontent.com/45184146/116504841-449b1e80-a887-11eb-917a-d36979901916.png)
I didn't realize, but apparently I'm only running openrgb-python 0.2.5 on windows. I'll try updating now and see if it causes the same issue on windows.

**Comment by jath03** [comment]
Just to make sure that the version has nothing to do with the issue, can you try forcing v1 on linux?

```python3
cli = OpenRGBClient(protocol_version=1)
```

**Comment by shawnc722** [comment]
Exact same message using v1, down to the byte that caused the error. I'll try downgrading to openrgb-python 0.2.5 on python to test that.

**Comment by jath03** [comment]
Actually, here's a more important question: exactly which OpenRGB commit broke it?

**Comment by shawnc722** [comment]
Okay I'm getting the same message on 0.2.5, which I was running on the same distro with no issues not very long ago. That's gotta mean the problem is coming from openrgb itself lol.
I haven't narrowed it down to the exact commit yet, but I'll try to do that now.

**Comment by jath03** [comment]
I just realized that this looks _very_ similar to #18, and you did recently add a device to OpenRGB.  Might [this function](https://gitlab.com/CalcProgrammer1/OpenRGB/-/blob/master/Controllers/AsusAuraGPUController/AsusAuraGPUController.cpp#L30-38) be returning something weird?

**Comment by shawnc722** [comment]
Actually just narrowed it down, it stopped working on [this](https://gitlab.com/CalcProgrammer1/OpenRGB/-/commit/bd3529b1d36e225207e564f9e958cd8bec2e0668) commit, which ironically was also to add a device I requested. Thanks for your help!

**Comment by shawnc722** [comment]
Yep, exactly the same problem as the issue you posted. I'm sorry to bother you for the same thing twice!
Thanks again for all your help.

**Comment by jath03** [comment]
I or someone should probably implement @inlart's the solution to #18 across all HID devices in OpenRGB.

**Comment by shawnc722** [comment]
Yeah, that's probably a good idea. I just borrowed his solution and recompiled, but it looks like the same problem is actually affecting my keyboard too, which I just added support for a few days ago.
I'll also stop starting my bug hunts over here, after making the issues on your repo when it's not to blame twice in a row lol. Thanks again!
