### ISSUE TITLE
Start / Stopping the client

### ISSUE THREAD

**Issue by bahorn** [jath03/openrgb-python#4]
When implementing a longer running client, I'd like the ability to be able to stop / start the connection to OpenRGB + handle disconnections a bit more gracefully.

Easiest way I can see to implement these would be:

### Start / Stopping

* Checking a variable instead of always evaluating to true on https://github.com/jath03/openrgb-python/blob/master/openrgb/network.py#L60
* Implementing some cleanup logic after this loop to close the socket
* Adding in two extra functions, one to start (basically move most of `__init__` into this, needs an extra check to ensure only one connection is active.) and a stop one to make the variable used by `listen` false.

### Better disconnecting handling

* Define a new exception like `OpenRGBDisconnected`
* Make `send_header` and `send_data` check if the sever is still active.
* Wrap every instance of `sock.recv_into` and `sock.send` with some exception handling, which will stop the client if it throws one.
* Then raise the `OpenRGBDisconnected` exception so the user can catch all these errors.

I'm fine implementing these if you want!

**Comment by jath03** [comment]
While trying to find ways to make it possible to both have correct internal state and be able to run very fast, I realized that the main bottleneck was that listen loop.  I'm working on removing the loop from the listen function and making it something that would be called when expecting data, somewhat similar to the `recv_message` function from your library.  I'll implement the start and stop functions after removing the loop and leave the disconnect handling to you.
