### ISSUE TITLE
set_color of LED Class doesn't take into account zones

### ISSUE THREAD

**Issue by Mauro-Rizzi** [jath03/openrgb-python#43]
Well the problem is pretty simple, if one of the devices has more than 1 zone and you want to change the color of a specific LED in a specific zone you run into "undefined" behavior that makes it so the LED of the last zone (i think it's the last one) you touched with the same ID gets modified.

Looking into the source you can find this:

 def set_color(self, color: utils.RGBColor, fast: bool = False):
        '''
        Sets the color of the LED
        :param color: the color to set the LED to
        :param fast: If you care more about quickly setting colors than having correct internal state data, then set :code:fast\ to :code:True
        '''
        self.comms.send_header(
            self.device_id,
            utils.PacketType.RGBCONTROLLER_UPDATESINGLELED,
            struct.calcsize("i3bx")
        )
        buff = struct.pack("i", self.id) + color.pack()
        self.comms.send_data(buff)
        if not fast:
            self.update()

As you can see this method makes no reference to the zone in any part, meaning you can't actually change individual leds from different zones

To replicate grab a device with multiple zones and do a for loop of each zone changing the leds one by one. You'll find you'll get unexpected results.

EDIT: I grabbed the current version doing pip3 install openrgb-python

**Comment by jath03** [comment]
This was fixed in [8e93f2b](https://github.com/jath03/openrgb-python/commit/8e93f2bbe3fcceff5b68fd56949f73ec2050a89c), but there just hadn't been a pypi release since then.

**Comment by Mauro-Rizzi** [comment]
I can confirm this was fixed, doing multiple loops trough different zones now works correctly
