### ISSUE TITLE
Is there a function to "Rescan Devices" via the API?

### ISSUE THREAD

**Issue by erwin** [jath03/openrgb-python#60]
When USB devices disconnect and reconnect to OpenRGB, OpenRGB looses control of them and I have to "Rescan Devices" in the UI.

I was hoping to use the openrgb-python client to trigger "Rescan Devices" but I could not find a function for that in the documentation and I couldn't find anything in the source called `rescan`...

![image](https://user-images.githubusercontent.com/11534217/186900041-299de4a0-c57a-4efa-bcac-44eadce23430.png)

**Comment by jath03** [comment]
Currently there is no way for SDK clients to trigger a rescan.  Because this functionality would have to exist on OpenRGB's SDK server first, I'm going to close this issue and recommend opening an issue over on the OpenRGB gitlab and/or asking about it on the discord.

**Comment by erwin** [comment]
Great. I thought it might be in there but I had just missed it.

Thanks so much for taking the time to read that and advising on what to do next!
