### ISSUE TITLE
OpenRGB [WinError 10061] 

### ISSUE THREAD

**Issue by AvexCodes** [jath03/openrgb-python#9]
Heyo, i'm trying to use this library and i'm getting this error. 

`ConnectionRefusedError: [WinError 10061] No connection could be made because the target machine actively refused it`

This is my current code.
```py
from openrgb import OpenRGBClient

client = OpenRGBClient("192.168.0.51", 8000)

print(client.devices())
```

**Comment by jath03** [comment]
Did you start OpenRGB's SDK server?  If so, are you sure that's the right port?  Unless you manually changed it when starting the server, the port is 6742.  If the port is correct, make sure there's no firewall or anything blocking the connection.  If you have checked all of this, maybe try the solution from [the question](https://stackoverflow.com/questions/20437701/winerror-10061-no-connection-could-be-made)
